app:
  prefix: /dailyHotSearch
cors:
  # origin: http://192.168.1.191:3001
  origin: http://192.168.5.221:3301
  methods: [GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS]
  credentials: true
  allowedHeaders: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Authorization']
  # preflightContinue: false
  # optionsSuccessStatus: 204
