app:
  prefix: /hotSearch
cors:
  # origin: http://localhost:3000
  origin: http://192.168.5.218:3001
  methods: [GET, POST, PUT, DELETE, PATCH, HEAD]
  preflightContinue: false
  optionsSuccessStatus: 204
