app:
  prefix: /dailyHotSearch
cors:
  origin: http://192.168.5.221:3301
  # origin: https://www.lukaka.work
  methods: [GET, POST, PUT, DELETE, PATCH, HEAD]
  preflightContinue: false
  optionsSuccessStatus: 204
